# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import Qt, QtCore, QtGui, QtWidgets
import sys
from GNURadioPortion import CarterCustomFMDemodSimulinkPort
import sip


class Ui_MainWindow(object):
    is_flowgraph_active: bool = False


    # Changes the RF Gain inside the flowgraph program and reflects the change in the UI
    def change_rf_gain(self):
        current_rf_value = round(self.RFSelector.value())
        current_rf_label = str(current_rf_value) + " [dB]"
        self.RFDisplay.setText(current_rf_label)
        self.tb.set_rf_gain(current_rf_value)

    # Changes the desired center frequency inside the flowgraph program and reflects the change in the UI
    def change_frequency(self):
        if self.is_flowgraph_active:
            current_freq_value: float = round((self.FrequencySelector.value() * 0.2) + 88.1, 1)
            current_freq_label = str(current_freq_value) + " [MHz]"
            self.FrequencyDisplay.setText(current_freq_label)
            current_freq_value = current_freq_value * 1e6
            self.tb.set_center_frequency(current_freq_value)

    # Toggles whether the radio is on or off
    def change_start_stop(self):
        if self.is_flowgraph_active:
            self.is_flowgraph_active = False
            self.StartStopButton.setText("Start")
            self.tb.stop()
            self.tb.wait()
        else:
            self.is_flowgraph_active = True
            self.StartStopButton.setText("Stop")
            self.tb.start()

    # Connects Sliders and Button to their respective functions
    def connect_ui_elements(self):
        self.FrequencySelector.valueChanged.connect(self.change_frequency)
        self.StartStopButton.clicked.connect(self.change_start_stop)
        self.RFSelector.valueChanged.connect(self.change_rf_gain)

    # QT UI Setup created via QT Designer
    def setupUi(self, MainWindow):

        self.tb = CarterCustomFMDemodSimulinkPort()

        MainWindow.setObjectName("GNURadio FM Demodulator")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")

        # Start/Stop Button
        self.StartStopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartStopButton.setObjectName("StartStopButton")
        self.StartStopButton.setMinimumHeight(100)
        self.verticalLayout.addWidget(self.StartStopButton)

        # Waterfall Plot
        self.WaterfallPlot = QtWidgets.QWidget(self.centralwidget)
        self.tb.qtgui_waterfall_sink_x_0.set_title("")
        self.tb.qtgui_waterfall_sink_x_0.set_time_title("")
        self.tb.qtgui_waterfall_sink_x_0.enable_axis_labels(False)
        self.waterfall_sink_widget_instance = self.tb.qtgui_waterfall_sink_x_0.qwidget()
        self.tb._qtgui_waterfall_sink_x_0_win = sip.wrapinstance(self.waterfall_sink_widget_instance, Qt.QWidget)
        self.WaterfallPlot.setFocusPolicy(QtCore.Qt.NoFocus)
        self.WaterfallPlot.setAttribute(QtCore.Qt.WA_TransparentForMouseEvents, True)
        self.WaterfallPlot.setObjectName("WaterfallPlot")
        self.verticalLayout.addWidget(self.tb._qtgui_waterfall_sink_x_0_win)


        # Vertical Layout 2
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Frequency Label
        self.FrequencyLabel = QtWidgets.QLabel(self.centralwidget)
        self.FrequencyLabel.setTextFormat(QtCore.Qt.PlainText)
        self.FrequencyLabel.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        freq_label_font = self.FrequencyLabel.font()
        freq_label_font.setPointSize(24)
        self.FrequencyLabel.setFont(freq_label_font)
        self.verticalLayout_2.addWidget(self.FrequencyLabel)

        # Frequency Selector
        self.FrequencySelector = QtWidgets.QSlider(self.centralwidget)
        self.FrequencySelector.setMinimum(0)
        self.FrequencySelector.setMaximum(99)
        self.FrequencySelector.setSingleStep(1)
        self.FrequencySelector.setPageStep(1)
        self.FrequencySelector.setProperty("value", 49)
        self.FrequencySelector.setTracking(True)
        self.FrequencySelector.setOrientation(QtCore.Qt.Horizontal)
        self.FrequencySelector.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FrequencySelector.setTickInterval(1)
        self.FrequencySelector.setObjectName("FrequencySelector")
        self.verticalLayout_2.addWidget(self.FrequencySelector)

        # Frequency Display
        self.FrequencyDisplay = QtWidgets.QLabel(self.centralwidget)
        self.FrequencyDisplay.setObjectName("FrequencyDisplay")
        self.FrequencyDisplay.setTextFormat(QtCore.Qt.PlainText)
        self.FrequencyDisplay.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        freq_display_font = self.FrequencyDisplay.font()
        freq_display_font.setPointSize(18)
        self.FrequencyDisplay.setFont(freq_display_font)
        self.verticalLayout_2.addWidget(self.FrequencyDisplay)

        # RF Label
        self.RFLabel = QtWidgets.QLabel(self.centralwidget)
        self.RFLabel.setTextFormat(QtCore.Qt.PlainText)
        self.RFLabel.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.RFLabel.setObjectName("RFLabel")
        rf_label_font = self.RFLabel.font()
        rf_label_font.setPointSize(24)
        self.RFLabel.setFont(rf_label_font)
        self.verticalLayout_2.addWidget(self.RFLabel)

        # RF Selector
        self.RFSelector = QtWidgets.QSlider(self.centralwidget)
        self.RFSelector.setMinimum(0)
        self.RFSelector.setMaximum(60)
        self.RFSelector.setSingleStep(1)
        self.RFSelector.setPageStep(1)
        self.RFSelector.setProperty("value", 30)
        self.RFSelector.setTracking(True)
        self.RFSelector.setOrientation(QtCore.Qt.Horizontal)
        self.RFSelector.setObjectName("RFSlider")
        self.verticalLayout_2.addWidget(self.RFSelector)

        # RF Display
        self.RFDisplay = QtWidgets.QLabel(self.centralwidget)
        self.RFDisplay.setTextFormat(QtCore.Qt.PlainText)
        self.RFDisplay.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.RFDisplay.setObjectName("RFDisplay")
        rf_display_font = self.RFDisplay.font()
        rf_display_font.setPointSize(18)
        self.RFDisplay.setFont(rf_display_font)
        self.verticalLayout_2.addWidget(self.RFDisplay)

        # Stretch Mode
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        # Menu Bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # Status Bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tb.connect((self.tb.rtlsdr_source_0, 0), (self.tb.qtgui_waterfall_sink_x_0, 0))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connect_ui_elements()
        self.change_start_stop()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("GNURadio FM Demodulator", "MainWindow"))
        self.FrequencyLabel.setText(_translate("MainWindow", "Center Frequency"))
        self.FrequencyDisplay.setText(_translate("MainWindow", "97.9 [MHz]"))
        self.RFLabel.setText(_translate("MainWindow", "RF Gain"))
        self.RFDisplay.setText(_translate("MainWindow", "30 [dB]"))
        self.StartStopButton.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
